### PR TITLE
Use maven-publish plugin for publishing to local maven repository

### PR DESCRIPTION
**Pull request by karlicoss**
Provides `publishToMavenLocal` Gradle task, useful to test out the library locally.

### CODE REVIEW

**Comment by nevenz** [comment]
Is this all it takes? It doesn't do anything for me, unless I add something like:
```
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
```

**Comment by karlicoss** [comment]
Hm, yup, pretty sure it worked yesterday; although could try again today. Anyway, how do you usually do it by yourself? I was playing with Orgzly source code, and apparently it relied on some (unpublished to maven central) code in this repo, I only managed to build orgzly after installing this to local maven.

**Comment by nevenz** [comment]
> Anyway, how do you usually do it by yourself? I was playing with Orgzly source code, and apparently it relied on some (unpublished to maven central) code in this repo, I only managed to build orgzly after installing this to local maven.

This was just fixed in orgzly/orgzly-android#306

Also, see `sample.app.properties` in `orgzly-android` - you can set `org_java_directory` in `app.properties` too.

**Comment by karlicoss** [comment]
Ah I see, ok! Thanks; feel free to close if you don't find this useful :)

**Comment by nevenz** [comment]
We can add it we it becomes needed in the future, thanks.

**Pull request closed without merging**
